apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - rules.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - webhook-receiver.yaml
commonLabels:
  managed-by: devops-lab
  week: "4"
  day: "21"
