apiVersion: v1
kind: Service
metadata:
  name: mobilebank-api
  namespace: mobilebank
  labels:
    app: mobilebank-api
spec:
  # ClusterIP: el trafico externo entra via Ingress (Week 3 - Day 13)
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: mobilebank-api
