apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay para PRODUCTION (Week 3)
namespace: mobilebank-production

resources:
  - ../../base

commonLabels:
  environment: production
  tier: production

patches:
  - path: patches/replicas.yaml
    target:
      kind: Deployment
      name: mobilebank-api
  - path: patches/configmap.yaml
    target:
      kind: ConfigMap
      name: mobilebank-config
  - path: patches/ingress-host.yaml
    target:
      kind: Ingress
      name: mobilebank-api
  - path: patches/hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: mobilebank-api
  - path: patches/pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: mobilebank-data
