{
 "title": "MobileBank - Overview",
 "tags": [
  "mobilebank",
  "week4"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Pods UP por environment",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-pods\",app=\"mobilebank-api\"} == 1) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "HTTP request rate (req/s)",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(mobilebank_http_requests_total[1m])) by (method, endpoint)",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Latencia p95 (ms)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mobilebank_http_request_duration_seconds_bucket[5m])) by (le, endpoint)) * 1000",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Transferencias por minuto",
   "type": "graph",
   "gridPos": { "x": 0, "y": 12, "w": 9, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(mobilebank_transfers_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pod CPU (cores)",
   "type": "graph",
   "gridPos": { "x": 9, "y": 12, "w": 9, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"mobilebank-.*\",pod=~\"mobilebank-api.*\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}